### ISSUE TITLE
Graphics tests failing on Travis-CI

### ISSUE THREAD

**Issue by davidchall** [topasmc/qc-testsuite#2]
As can be seen in [the latest Travis-CI results](https://magnum.travis-ci.com/topasmc/topas/builds/12229601), all the Geometry_\* tests are failing on the Travis-CI machines. This occurs even though the OpenGL libraries are present, which are required during the build.

I thought this might be because the Travis-CI nodes were unable to open a window, so I used an X virtual buffer (https://github.com/topasmc/topas/commit/ead1652795bbc331bbb87e9af17508521ef7897a) and suggested in the [Travis-CI documentation](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29). However, this didn't resolve the issue.

I can either:
- look at the stdout and stderr from these jobs and contact Travis-CI about using OpenGL
- replace OpenGL with HepRep output in these tests

@jiperl is there any reason not to just switch to HepRep for these tests? This might also give a nicer file comparison against a benchmark, rather than comparing an eps file.

**Comment by jiperl** [comment]
Switching to HepRep is a very good idea for these tests.
The HepRep file contains not just graphical information but also physics
attributes (momenta, particle type ID, etc.) for the trajectories. It puts
more information into the results.

**Comment by davidchall** [comment]
Here is the stderr:

```
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--10-100-75-75-m-60-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--11-80-100-100-m-60-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--12-120-75-75-m-70-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--14-100-100-100-m-90-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--17-120-100-100-m-100-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--18-180-75-75-m-110-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--20-140-100-100-m-110-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--24-240-75-75-m-150-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--25-180-100-100-m-150-iso8859-1
G4OpenGLXViewer::CreateFontLists XLoadQueryFont failed for font-adobe-courier-bold-r-normal--34-240-100-100-m-200-iso8859-1
```

So it appears this is actually a font problem, rather than a problem using the virtual framebuffer.

However, if we both agree that outputting HepRep is in fact a nicer test, then I'll make this change. The only problem is that it no longer tests the graphical components of TOPAS.

**Comment by jiperl** [comment]
Best would be to still have a few tests that also use OpenGL, but that area
of the code is not very likely to have any new problems creep in.
Once one gets to choosing between different graphics drivers, the code
differences are all on the Geant4 side, and really nothing in the TOPAS
layer, so we wouldn't be testing anything that our Geant4 visualization
group doesn't test anyway.
Also, just in the course of daily use, I exercise the OpenGL layer on at
least a few operating systems pretty heavily.
So, I think for now at least, it's fine to switch the tests to HepRep.

**Comment by davidchall** [comment]
Fixed by https://github.com/topasmc/qc-testsuite/commit/c07fca21c3d8bb725ba88c349a2936dd363c9a18
